Program("rpc_test", ["myrpc.cpp", "request.cc", "callable.cpp", "session.cpp", "stream_tcp_socket.cpp"], 
        CPPPATH = ["../../OUT/include",
                   "inc",
                  "/home/vasily/Projects/efr_new/Boost/include"],
        LIBPATH = ["/home/vasily/Projects/efr_new/Boost/bin/i386_linux",
                   "../../OUT/lib"],
        LIBS = ["msgpack", "boost_thread", "boost_system"]
        )
