Program("rpc_test", ["target/test/test.cpp", "src/request.cc", "src/callable.cpp", "src/session.cpp", "src/stream_tcp_socket.cpp",
                     "src/tcp_client.cpp", "src/tcp_server.cpp"], 
        CPPPATH = ["../../OUT/include",
                   "./",
                  "/home/vasily/Projects/efr_new/Boost/include"],
        LIBPATH = ["/home/vasily/Projects/efr_new/Boost/bin/i386_linux",
                   "../../OUT/lib"],
        LIBS = ["msgpack", "boost_thread", "boost_system"]
        )
